- .github/workflows/ci.yml
- .gitignore
- scripts/ci-build.sh
- scripts/ci-create-debian-package.sh
- scripts/ci-create-rpm-package.sh
- Update package creation.
- Build with `--disable-termcap`.
> Update package creation.

- README.md
- scripts/ci-build.sh
- scripts/ci-create-debian-package.sh
- scripts/ci-create-nuget-package.sh
- scripts/ci-create-rpm-package.sh
- scripts/ci-prepare-artifacts-for-upload.sh
- Update CI to create separate packages for `zsv` and `zsvlib`.
- Resolves #23.
> Update CI to create separate packages for zsv and zsvlib

- .github/workflows/ci.yml
- .gitignore
- scripts/ci-update-homebrew-tap.sh
> [CI] Update homebrew tap on tag/release.

- .github/workflows/ci.yml
- The [`branches` filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters) is not available on the [`release`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) event.
- Linted this [commit](https://github.com/liquidaty/zsv/commit/7a345db10837c610bddcd303c7da9e33b1bbd800) and it's now [error free](https://rhysd.github.io/actionlint/#eJztWm1v2kgQ/s6vGHFRSaOunbeLKk6pShKSoiYkAnJpVUXI2IvZxl67Xps0bfPfb9bvxgbSu2uL7vjCy+7M+pl55s1grtm0CTqr1RzerAG4gZjId4CRp3F9QkUTPtga47fhoqv5E0GYyR2PRmIE6ltbim3UQ2XLGnr0U0CF/7cP8ahFNRFv+A9uqOwGI4uJCTVua7WPzkjIXZ1FMjwxQX4Rvqf51HyItgBszffY5+QbgCNPC0YB9wOyu61s779AEd0RZGcXj5YSXsAFQWfAxtevsbriCHh8jLYpnyanDVpnTahvK3vKbj1eal2cHOwPzzvd63fDs+PjJmi2cbBPLMaDz8TU9Qqx4/NW96woqFsaNwuiN53uy …
> [CI] Remove branches filter from release event.

- app/cli.c
- app/test/Makefile
> finish cmd-help-fix

- app/Makefile
- app/utils/cache.c
- app/utils/os.c
- include/zsv/utils/os.h
…ok on posix, but failed on win)
> fix zsv_replace_file trying to rename file before closing

- Makefile
- app/Makefile
- app/compare.c
- app/compare_internal.h
- app/compare_sort.c
- app/sql.c
add "make check" synonym for "make test"
clean up unused/dead comments
fix sql --join-indexes bug when > 2 files joined
support custom sql stmt together with --join-indexes
> misc updates (make check, sql, compare)

- app/compare_unique_colname.c
fixes this issue due to a bug in colname comparison
> fix 139: compare files if input has duplicate column names

- app/Makefile
- app/builtin/help.c
- app/ext_example/Makefile
- app/ext_example/test/expected/zsvext-test-3.out
- app/select.c
- configure
- include/zsv/api.h
- include/zsv/utils/dirs.h
- scripts/ci-build.sh
- src/zsv.c
> fix cum_scanned_length tracking for files larger than initial read buff

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- Configure CodeQL
- Source + Tests
Check its results on my fork under:
- Security (https://github.com/iamazeem/zsv/security)
- Code scanning (https://github.com/iamazeem/zsv/security/code-scanning)
Alerts' count:
- without tests: 15
- with tests: 20
> Integrate CodeQL

- .github/workflows/ci.yml
> [CI] Attest build artifacts

- .dockerignore
- .github/workflows/ci.yml
- Dockerfile
- app/Makefile
- scripts/ci-build.sh
- Build docker image on every push/PR
- Publish built docker image on release with respective tag
- Resolves #211
> [CI] Publish Docker image (WIP)

- .github/workflows/benchmarks.yml
- scripts/ci-run-benchmarks.sh
- Separate jobs for macOS and Linux builds
- Update script to handle macOS and Linux builds
- Update to run locally and CI both
> [CI] Benchmarks updates

- scripts/ci-run-benchmarks.sh
- Minor summary updates for better UI/UX
> [CI] Benchmarks' summary updates

- .github/workflows/benchmarks.yml
- scripts/ci-run-benchmarks.sh
- Remove redundant inputs/env vars
- Add input to specify RUNS
- Add [xychart](https://mermaid.js.org/syntax/xyChart.html) for averages with mermaid for GitHub Actions summary
- Other miscellaneous cleanup and updates
> [CI] Benchmarks enhancements (chart, etc.)

- app/test/Makefile
- playground/index.html
- Add tag for favicon
- Fix dangling tmux session of `test-sheet-1`
> Fix favicon and exit dangling test-sheet-1 session

- .github/workflows/ci.yml
- playground/index.html
- Separate build step for non-SIMD playground
- Update `index.html` to load non-SIMD version for iOS
- Reference #313 
> Support zsv payground on iOS

- .github/workflows/ci.yml
> [CI] Updates for deprecated changes

- app/cli.c
- app/ext_example/mysheet_extension.c
- app/sheet.c
- app/sheet/handlers.c
- app/sheet/handlers_internal.h
- app/sheet/sheet_internal.h
- app/sheet/transformation.c
- include/zsv/ext.h
mysheet_extension: properly consider has_row_num
> sheet api: add ext_sheet_buffer_info()

- app/builtin/register.c
- app/cli.c
- app/cli_ini.c
- app/utils/dirs.c
- include/zsv/utils/dirs.h
change zsv.ini paths to more conventional
> register: add -g,--global

- playground/index.html
- Introduce `download` command to download files from URL(s)
- Update wiki (https://github.com/liquidaty/zsv/wiki/zsv-playground)
> [Playground] Add `download` command

- .github/workflows/codeql.yml
- Update runner
- Configure for GitHub Actions workflow security analysis
- Skip archives (not needed)
- Resolves #391
> CodeQL updates

- .github/workflows/ci.yml
- .github/workflows/setup-action.yml
- Added `permissions`
- Skipped `setup-action` test workflow in the main CI workflow
- Resolves #393
> Add `permissions` in `setup-action` test workflow

- .github/workflows/ci.yml
- scripts/ci-prepare-deb-rpm-repos.sh
> [CI] LInux deb/rpm repos updates

- .github/workflows/ci.yml
Resolves #406.
- Introduced manual trigger with Boolean flag to enable the WSL job (default is `false`)
> [CI] WSL manual trigger
