liquidaty/zsv

.github/workflows/ci.yml, scripts/ci-create-debian-package.sh, scripts/ci-create-nuget-package.sh, scripts/ci-create-rpm-package.sh, scripts/ci-prepare-artifacts-for-upload.sh
=> CI updates

.github/workflows/ci.yml, BUILD.md, README.md, app/Makefile, app/utils/os.c, docs/csv_json_sqlite.md
- Use GCC 11 instead of clang for macosx build.
- Resolves #30.
=> Use GCC 11 instead of clang for macosx build.

README.md
- Update README for macosx homebrew tap instructions.
- Related #34.
**NOTE**: Should only be merged after the transfer of ownership of https://github.com/iamazeem/homebrew-zsv is complete.
=> Update README for macosx homebrew tap instructions.

app/select.c, app/utils/arg.c, app/utils/writer.c
change zsv_with_default_opts() to ensure max_row_size and max_columns are always 0 to fix bug that may show up up in consecutive runs when instance is left open e.g. in emcc
=> fix tiny mem leak when `select` cmd run with trailing blank header rows

src/zsv_internal.c
=> fix potential multi-span header corruption from memcpy vs memmove

app/desc.c, app/test/Makefile, app/test/expected/test-desc.trim, data/test/desc-trim.csv, examples/js/README.md
=> fix typo in examples/js/README.md

.github/workflows/ci.yml
- `macos-10.15` is deprecated.
- FreeBSD action (https://github.com/vmactions/freebsd-vm) v0 is available for `macos-12` only.
- Use `macos-12` for all macOS workflow.
- Use `actions/checkout@v3`. Its `v2` is deprecated.
- Updates #83.
=> [CI] Use macos-12 instead of macos-10.15.

.github/workflows/ci.yml
- Resolves #96.
- Removes archived [action-get-tag](https://github.com/dawidd6/action-get-tag).
=> [CI] Fix release workflow warnings.

.github/workflows/ci.yml, scripts/ci-freebsd-setup.sh
The FreeBSD build action is failing for reasons due to problems with the action itself (https://github.com/vmactions/freebsd-vm/issues/74).
=> try to replace vmactions/freebsd-vm action with cross-platform-actions/action

app/utils/dirs.c, app/utils/dirs_from_json.c, app/utils/string.c, src/zsv.c, src/zsv_strencode.c
move zsv_strencode.c to standalone file
change utils/dirs_from_json to accommodate backslash path separators modify zsv_foreach_dirent to stop sooner if max_depth provided and to abort if subdir handler returns err
=> misc refactorings

.github/workflows/ci.yml
Update actions/checkout, actions/upload-artifact, and cross-platform-actions/action to fix NodeJS 16 deprecation warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Latest run with deprecation warnings: https://github.com/liquidaty/zsv/actions/runs/8260147411
=> [CI] Update actions versions to fix NodeJS 16 deprecation warning

.github/workflows/ci.yml
=> [CI] Use Linux (Ubuntu) for FreeBSD

.github/workflows/ci.yml
- Build AMD64 on `macos-12`
- Build ARM64 on `macos-14`
- Update homebrew tap only under `macos-12`
Fixes #158.
=> [CI] Build for macOS ARM64

README.md
Previous installation in README.md for Windows using choco.exe changed so it points at directory .nupkg file is in, not at the .nupkg file itself
=> Update README with correct Chocolatey installation instructions

include/zsv/api.h, src/zsv.c
and fix zsv_cum_scanned_length if called during final() with input that has no final trailing row end
=> add zsv_row_length_raw_bytes

.clang-format, .github/workflows/ci.yml, app/pretty.c, app/rm.c, app/select-pull.c, app/select.c, app/sql.c, scripts/ci-run-clang-format.sh, src/zsv_internal.c
- Minor cleanup for code scan
- Use `clang-format-15`
- Format source files if required (missing ones)
=> minor cleanup for code scan

.cppcheck, .github/workflows/ci.yml, .gitignore, Makefile, app/utils/dirs.c, scripts/ci-run-cppcheck.sh
- Add `.cppcheck` file for project configuration
- Cppcheck manual: https://github.com/danmar/cppcheck/blob/main/man/manual.md
- Add shell script to run `cppcheck` and generate XML and HTML reports
- Configure CI workflow to run cppcheck script
- Upload XML and HTML reports as artifacts
- Add navigable Cppcheck summary in the CI's step summary as Markdown
- Update `.gitignore`
- Resolves #195
=> [CI] Integrate Cppcheck for static code analysis

.github/workflows/ci.yml, app/Makefile, app/sheet.c, app/sheet/read-data.c, app/test/Makefile, app/test/expected/test-sheet1.out, app/test/expected/test-sheet2.out, app/test/expected/test-sheet3.out, configure
- Use `tmux` to automate interactive `sheet` command tests
- `tmux` getting started: https://github.com/tmux/tmux/wiki/Getting-Started
- Helpful `tmux` scripting reference: https://tao-of-tmux.readthedocs.io/en/latest/manuscript/10-scripting.html
- Resolves #209 
=> Add automated tests for `sheet` command

app/test/Makefile, app/test/expected/test-sheet4.out
- Separate setup test and reuse it for the rest
- Add tests for navigation using SHIFT keys
- Resolve #212
=> [CI] Update `sheet` command tests

.github/workflows/ci.yml, README.md
- Publish docker container image to GHCR
- With published `version` (tag) and `latest` too on release
- Update README
=> [CI] GHCR and docker image updates

.github/workflows/ci.yml, .github/workflows/setup-action.yml, README.md, setup-action/README.md, setup-action/action.yml, setup-action/scripts/setup.bash
- Add custom GHA composite action to install zsv+zsvlib
- Add CI workflow to test it
- Add README
- Update main README with an example and link
=> Add zsv/setup-action for GHA workflows

.github/workflows/ci.yml
- On release, use the release tag
- On non-release CI runs, fetch latest tag and use that
- No need to hardcode version in the CI workflow for non-release builds
- In addition, enable container build on all builds
- Enable push only on release
- Resolves #87
=> [CI] Version updates + enable GHCR/container builds

.github/workflows/ci.yml, scripts/ci-run-cppcheck.sh, scripts/ci-set-tag-output-parameter.sh, scripts/ci-upload-release-artifacts.sh, scripts/ci-verify-attestations.sh
- Separate job for BSD build to run it in parallel
- Should save ~2 minutes
- Move inline scrips to their respective files
- Make Cppcheck table output collapsible
- Attest release artifacts only
- Minor cleanup
=> [CI] Separate job for BSD build + other cleanup

.github/workflows/ci.yml, .shellcheckrc, app/test/select-quotebuff-gen.sh, scripts/ci-create-debian-package.sh, scripts/ci-run-shellcheck.sh
- Print tty summary in console logs by default
- Post tty and diff logs in GitHub step summary (collapsible)
- Add `.shellcheckrc` to disable diagnostic(s) globally
- Lint and fix issues in existing scripts
- For now, the CI will just report shellcheck issues
- In future, it may be updated as needed e.g. fail on issues
- Resolves #192 
=> [CI] Integrate shellcheck

configure
- Fix linting issues
- Fix indentation issues
- Convert tabs to spaces
- Disable diagnostics for required stuff
=> Lint and fix `configure` script for `shellcheck` issues

app/sheet.c, app/sheet/key-bindings.c, app/sheet/key-bindings.h
Additions:
Add `zsvsheet_replace_cell` function.
Add `zsvsheet_key_replace` keybind, currently bound to `r`.
Currently, if the replace key is pressed, it will prompt the user to input the new value of the cell (by calling the `get_subcommand` function). It will then replace the contents of the cell with the user-inputted contents. 
I have not implemented support for long-cells yet, so if the text is too long it will report that to the user using the `zsvsheet_set_status` function, and not replace the cell contents.
Attached is a video demo of the functionality.
https://github.com/user-attachments/assets/2714b0cd-78e4-4528-9840-98b853c652d3
=> Add overwrite functionality to sheet

.github/workflows/benchmarks.yml, .github/workflows/ci.yml, scripts/ci-run-benchmarks.sh
- Use build artifacts from other workflow runs using the run ID (optional)
- Use the latest released build otherwise
=> [CI] Add benchmarks' enhancements

app/Makefile, app/sheet.c, app/sheet/index.c, app/sheet/index.h, app/sheet/read-data.c, app/sheet/ui_buffer.c, app/test/Makefile, app/utils/index.c, include/zsv/common.h, include/zsv/utils/index.h
Move the basic in-memory index functionality into utils and rework the API to make it easier to use. There is now a seek function which moves the file offset to the exact line-end requested by the user.
The temp file generation has not been moved into utils because generalising it started to introduced a lot more callbacks and other complications.
This also changes the sheet display code so that (building index) is displayed in the status area while indexing is in progress.
=> Cleanup and modularize index

.gitignore, app/Makefile, app/select.c, app/utils/signal.c, examples/js/Makefile, examples/js/README.md, examples/js/browser/zsv-browser-example.js, include/zsv/utils/signal.h
- Fix some build issues encountered locally
- Fix README typo
- Update `alert` message format for better UX e.g. two decimal places for elapsed time in milliseconds, etc.
- Ignore generated files
=> Fix local wasm build issues on Ubuntu 22.04 LTS

scripts/ci-run-benchmarks.sh
- Fix command for `tsv-select`
- The output was different for `tsv-select`.
- Fixing the command fixed the output.
- Now, the output is same for `zsv`, `xsv`, and `tsv-select`.
- For count tests, the equivalent command from `tsv-utils` seems to be [`tsv-summarize --count`](https://github.com/eBay/tsv-utils/blob/master/docs/tool_reference/tsv-summarize.md) instead of [`number-lines`](https://github.com/eBay/tsv-utils/blob/master/docs/tool_reference/number-lines.md).
- Now, the output is similar for all three tools except that counting of header row.
Here's the output of the equivalent count commands:
```shell
$ zsv count < worldcitiespop_mil.csv 
1000000
$ xsv count --no-headers < worldcitiespop_mil.csv 
1000001
$ tsv-summarize --count -d, < worldcitiespop_mil.csv 
1000001
```
Currently, …
=> Fix benchmarks commands

.github/workflows/ci.yml, app/sheet/index.c, app/sheet/index.h, app/sheet/read-data.c, app/test/Makefile, app/test/expected/test-sheet-8.out
The properties file was overriding opts.rows_to_ignore and
opts.header_span values that need to be set to zero when using an
index. This recreates the parser with zsv_new after the opts have
been rewritten when an index is active.
=> sheet: Override header span and skip rows when using properties file

app/overwrite.c
Fixes the warnings in the attached image.
=> Fix cppcheck issues in overwrite.c

app/sheet.c, app/sheet/key-bindings.c, app/sheet/key-bindings.h, app/sheet/procedure.c, app/sheet/procedure.h, app/test/Makefile, app/test/expected/test-sheet-13.out, app/test/expected/test-sheet-14.out
This adds a help buffer activated by pressing '?'
The initial version is slightly different from planned because it uses 3 columns instead of 1 to help with layout.
TODO:
=> Add help buffer

app/builtin/register.c, app/cli.c, app/cli_ini.c, app/compare.c, app/compare_internal.h, app/compare_sort.c, app/curses.h, app/ext_example/Makefile, app/ext_example/mysheet_extension.c, app/external/sqlite3/sqlite3_csv_vtab-mem.c, app/external/sqlite3/sqlite3_csv_vtab-mem.h, app/external/sqlite3/sqlite3_csv_vtab-zsv.c, app/external/sqlite3/vtab_helper.c, app/sheet.c, app/sheet/handlers.c, app/sheet/handlers_internal.h, app/sheet/index.c, app/sheet/read-data.c, app/sheet/screen_buffer.c, app/sheet/ui_buffer.c, app/sql.c, app/sql_internal.c, app/sql_internal.h, include/zsv/ext.h, include/zsv/utils/sql.h
This extension adds a command invoked by 'v' that runs a very simple pivot table
TO DO:
- change hyperlink formatting to only be on data rows
- remove row numbers from pivot table output
- add drill-down handler that will display source data drill-down
- requires temp file ref counter so that if prior buffer uses temp file and is closed, the related temp file will still exist in order to run drill-down
=> Cell highlighting v2

app/builtin/help.c, app/ext_example/test/expected/zsvext-test-3.out, app/test/Makefile, app/test/overwrite/Makefile
test/overwrite/Makefile: make test-timestamp more flexible for fewer false fails, remove trailing white
=> add --apply-overwrites option description to help message

README.md, data/bulkdata.csv, data/mydata.csv, docs/overwrite.md
The pull request is simple, it just adds a file which documents the usage of the `overwrite` command. Similar to the `docs/compare.md` documentation file.
There is a basic overview of the functionality, basic usage and layout of commands and options, a description of the command, examples of how the command works (with input and output data), an explanation of the SQLite database, and the help message for the command.
=> Add documentation file for `overwrite` command

.github/workflows/ci.yml
- Refer to the failed job on release: https://github.com/liquidaty/zsv/actions/runs/12230465958/job/34111840491
- Update CI to install GitHub CLI before running verification command
- Tested locally with `apk add github-cli` but the installed version was an older one i.e. 2.47.*
- It wasn't able to verify correctly.
- Installing the latest version (https://github.com/cli/cli/releases/download/v2.63.2/gh_2.63.2_linux_amd64.tar.gz) worked fine.
=> [CI] Fix attestations' verification for musl build

.github/workflows/ci.yml, scripts/ci-update-homebrew-tap.sh
- Generated artifacts:
- ZIP: **with** codesigning and notarization
- TAR: **without** codesigning and notarization (default for `homebrew-zsv` tap)
=> [CI][MAC] Generate artifacts with and without codesigning

app/utils/os.c, include/zsv/utils/os.h
If a file is being moved across devices then rename() won't work. The
file needs to be copied instead.
/tmp and /home are on separate drives on one of my machines. I can't save the config and load extensions without on that machine without this.
=> util: Add rename fallback for copying across devices

playground/index.html
Related: #374
- Enabled buffering and truncation for STDOUT
- Added `less` command to optimize the viewing of large files
- Enabled autocompletion and added in `help` text
- Added STDIN and pipe support
- e.g. `zsv echo file.csv | less`
- Removed wiki page
- Added usage and notes in `help` text instead to keep it at one place together
- Added ASCII table for to automate and beautify the `help` command text and `config` output
- Added elapsed time for `zsv` commands (terminal + developer console)
- Added `config` command to configure elapsed time and output truncation
Following are the comparisons when the output is buffered first and flushed only
after it is available i.e. no frequent calls for flushing output.
```shell
zsv echo -L 500 worldcitiespop_mil.csv -o w500.csv
zsv 2json w500.csv …
```
=> [playground] Enable buffering; add `less` command and elapsed time

.github/workflows/ci.yml, playground/index.html, scripts/test-expect.sh, scripts/test-retry-capture-cmp.sh
Apparently, the handling of time is different on macOS.
Observed following in https://github.com/liquidaty/zsv/actions/runs/15184719799/job/42703430039#step:5:1066:
```shell
test-sheet-2: 
real 0.40
user 0.02
sys 0.03
Invalid timing value! []
real 0.02
user 0.00
sys 0.01
Invalid timing value! []
...
```
The log `Invalid timing value! []` has recently been added while testing on WSL.
Looking at the older workflow runs, it seems like it's been broken for quite some time now.
Fixing this issue and adding more robust error handling to fail fast.
**UPDATE**
On macOS, the output of `time` command was not being redirected correctly due to the differences between `time` shell builtin and the `/usr/bin/time` executable.
See details here: https://askubuntu.com/questions/1054456/what-is-the-differenc …
=> [CI] Verify macOS tests (time handling issue)
